sonar.projectKey=test-java-project
sonar.projectName=Test Java Project
sonar.projectVersion=1.0
sonar.sources=test_proj
sonar.host.url=http://localhost:9000
sonar.token=sqp_30f8e1baa86b01cdcc430cc2a9879d6032f6f33d
